#!/bin/bash

# Get the current branch name
branch_name=$(git symbolic-ref --short HEAD)

# Extract the substring before the second dash symbol
substring=$(echo $branch_name | cut -d'-' -f1,2)

# Get the commit message file
commit_msg_file=$1

# Get the first lint of commit file
first_line=$(head -n 1 $commit_msg_file)

# Check if the commit message is empty
if [ -z "$first_line" ]; then
	# Add the substring to the start of the commit message in square brackets
	sed -i.bak -e "1s/^/[$substring]: \n/" $commit_msg_file
fi
